version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Optionally mount local volume for development
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development